#index:
#    path: /
#    controller: App\Controller\DefaultController::index
NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix:   /api/doc
controllers:
  resource: '../src/Controller/'
  type: annotation
  prefix:
    en: '/en'
    fr: '/fr'






